[project]
name = "file_conversor_choco"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "Andre Luiz Romano Madureira", email = "fileconversor@gmail.com" },
]
dependencies = ["jinja2>=3.1.6", "autopep8>=2.3.2", "requests>=2.33.1"]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "Apache-2.0" }


[tool.pdm]
distribution = false
