# .github/workflows/publish.yaml

name: Publish Chocolatey Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-manifest:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting env variables
        run: |
          NAME="$(basename *.nuspec .nuspec)"
          VERSION=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          OUTPUT_DIR="dist"

          echo "NAME=${NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
          
          echo "Environment vars:"
          echo "NAME=${NAME}"
          echo "VERSION=${VERSION}"
          echo "OUTPUT_DIR=${OUTPUT_DIR}"
        shell: bash

      - name: Build Choco Package
        run: |
          choco pack -y --outdir "${OUTPUT_DIR}" *.nuspec
          ls -l "${OUTPUT_DIR}"
        shell: bash

      - name: Install Choco Package
        run: |          
          choco install -y --acceptlicense "${NAME}" --version="${VERSION}" --source="${OUTPUT_DIR};https://community.chocolatey.org/api/v2/"
        shell: bash

      - name: Test App Installation
        run: |
          ${NAME} --version
        shell: bash

      - name: Publish Choco Package
        run: |
          choco push ${OUTPUT_DIR}/*.nupkg --source https://push.chocolatey.org/ --apikey "${{ secrets.CHOCO_API_KEY }}"
        shell: bash
